### ISSUE TITLE
Installation of multiDA 

### ISSUE THREAD

**Issue by athomsvphd** [sarahromanes/multiDA#6]
Hi Author of multiDA! Just had a read of the package multiDA. Looks amazing and thought to implement it. By any chance, do you know which version of R does the package support? as it doesn't support version R 3.5.2. Many thanks in advance.

**Comment by sarahromanes** [comment]
Hey there!
This package was built using R 3.5.0! So not sure why it isn't working for 3.5.2. What error message do you get specifically and how are you trying to install it?

**Comment by athomsvphd** [comment]
Hi @sarahromanes, i'm trying to install using _install.packages("multiDA")_, it's shows which CRAN mirror to use, I choose the UK (London) and then it shows '_Warning message: package ‘multiDA’ is not available (for R version 3.5.2)_'. I've tried installing R.3.5.0 and tried the same, turned out vain. Any thoughts?

**Comment by sarahromanes** [comment]
Hi @AngelinaThoms , `multiDA` is not yet on CRAN! So you have to install using `devtools`. The instruction guide is on the README for this page, but you just have to type in the following
```
# Install the development version from GitHub:
# install.packages("devtools")
devtools::install_github("sarahromanes/multiDA")
```
Hope this helps!

**Comment by athomsvphd** [comment]
Hey @sarahromanes, it works now. Thanks a million! Cheerios! :)
